#!/bin/bash

python3 -m pytest --verbose --numprocesses=auto -t 2000 --ignore=scripts/copy_from_upstream/repos

rc=$?
if [ $rc -eq 0 ]; then
    echo "PASS: liboqs"
else
    echo "FAIL: liboqs"
fi
exit $rc

