#!/bin/bash

./qs-capability-check.py

rc=$?
if [ $rc -ne 0 ]; then
    echo "FAIL: liboqs"
    exit $rc
fi

python3 -m pytest --verbose --numprocesses=auto --ignore=scripts/copy_from_upstream/repos

rc=$?
if [ $rc -eq 0 ]; then
    echo "PASS: liboqs"
else
    echo "FAIL: liboqs"
fi
exit $rc
